version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: git clone https://github.com/sstephenson/bats.git
      - run: ./bats/install.sh .
      - run: ./bin/bats test/assume-role.bats
